### ISSUE TITLE
Adding Encrypt option

### ISSUE THREAD

**Issue by ButterMun** [clickteam-plugin/IniPlusPlus#1]
Unfortunately, this option does not work, so it would be great if it came back ;)

**Comment by LB--** [comment]
I've posted a new pre-release build with encryption support! Let me know if it works for you.

**Comment by ButterMun** [comment]
Alrighty, will check ;)06.09.2022, 08:00, "LB--" ***@***.***>:
I've posted a new pre-release build with encryption support! Let me know if it works for you.

**Comment by ButterMun** [comment]
Yup, that's working
Thank you for your work!
