### ISSUE TITLE
Can this be used in conjunction with existing INI++1.5 object?

### ISSUE THREAD

**Issue by Volnaiskra** [clickteam-plugin/IniPlusPlus#2]
Hi, 

I currently use 9 Ini++ 1.5 objects, connected to different files for different purposes. None of them require unicode, so are fine as is. Though I have one use-case where I will need unicode. It's a simple use-case, and the current iteration of the INI++1.6 object is probably more than enough for it. Though I don't think it would be ready for my existing 9 use-cases, as some of them use features that I don't believe are implemented in 1.6 yet (searching, reordering). 

Can I use both objects at once? In other words, could I keep my 9 existing INI++1.5 objects as they are, and add a INI++1.6 object for uses cases that require unicode, and the two extensions wouldn't conflict?

**Comment by JKage999** [comment]
> Hi,
> 
> I currently use 9 Ini++ 1.5 objects, connected to different files for different purposes. None of them require unicode, so are fine as is. Though I have one use-case where I will need unicode. It's a simple use-case, and the current iteration of the INI++1.6 object is probably more than enough for it. Though I don't think it would be ready for my existing 9 use-cases, as some of them use features that I don't believe are implemented in 1.6 yet (searching, reordering).
> 
> Can I use both objects at once? In other words, could I keep my 9 existing INI++1.5 objects as they are, and add a INI++1.6 object for uses cases that require unicode, and the two extensions wouldn't conflict?

Hello, can you upload compiled version of ini++ unicode please?

**Comment by LB--** [comment]
@Volnaiskra You might have some trouble in how Fusion tells apart extensions, all extensions have a unique ID so even if you have multiple copies (MFXs) the ID would be the same between them, so if they are actually different versions it might mean things like dragging actions between event columns would behave weirdly. It might work but I advise against it, and there is nothing I can do on my end to improve that experience. You should make frequent backups of your project and test various aspects regularly to make sure you're not corrupting things.
